"use client";
import react from "react";
import Head from "next/head";
import Login from "@/components/Login";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-100 min-h-screen">
        <Login />
      </main>

      <style jsx>{`
        .main-content {
          position: relative;
        }

        input {
          margin: 10px 0;
          padding: 8px;
          transition: background 0.3s ease;
        }

        input:hover {
          background-color: #f0f0f0;
        }

        button {
          padding: 8px 16px;
          background-color: #5566ipro;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
        }
      `}</style>
    </>
  );
}
